/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.codideep.app;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author KAAF0
 */
public class FrmList extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    
    /**
     * Creates new form FrmList
     */
    public FrmList() {
        initComponents();
        
        dtm.addColumn("DNI");
        dtm.addColumn("Nombre");
        dtm.addColumn("Apellido");
        
        jTableData.setModel(dtm);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader("miArchivo.txt"));
            
            String line;
            
            while((line = br.readLine()) != null) {
                String[] arrayLine = line.split("___");
                
                dtm.addRow(new Object[]{ arrayLine[0], arrayLine[1], arrayLine[2] });
            }
        } catch(Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableData = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        jTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido"
            }
        ));
        jScrollPane1.setViewportView(jTableData);

        btnDelete.setText("Eliminar registro seleccionado");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int rowSelected = jTableData.getSelectedRow();
        
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro para eliminarlo.");
            
            return;
        }
        
        try {
            List<String> listText = new ArrayList<>();
            
            BufferedReader br = new BufferedReader(new FileReader("miArchivo.txt"));

            String line;
            int index = 0;

            while((line = br.readLine()) != null) {
                if(rowSelected == index) {
                    index++;
                    
                    continue;
                }
                
                listText.add(line);
                
                index++;
            }
            
            FileWriter escritor = new FileWriter("miArchivo.txt");
            
            for(String item: listText) {
                escritor.write(item + "\n");
            }

            escritor.close();
        } catch(Exception e) {
        }
        
        dtm.removeRow(rowSelected);
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableData;
    // End of variables declaration//GEN-END:variables
}
